language: java

install: echo "My projects will be configurable in an awesomical way ;)."

# don't just run the tests, also run Findbugs and friends
script: mvn clean verify

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - mvn jacoco:report coveralls:report